"""Add year column to earthquakes

Revision ID: d9d53592ede1
Revises: 2a703d92c569
Create Date: 2025-06-12 00:19:52.149793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d53592ede1'
down_revision = '2a703d92c569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('earthquakes', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('earthquakes', 'year')
    # ### end Alembic commands ###
